version: '3.9'

services:
  database:
    restart: unless-stopped
    image: postgres:14.1
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    networks:
      - private
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - private

networks:
  private:
    external: true
    name: private
