###################################################################################
##                                                                               ##
## Read the instructions in the README_TEACHER.md file before running the file.  ##
##                                                                               ##
###################################################################################

version: '3.9'

services:
  app:
    build: .
    container_name: app
    env_file:
      - .env.teacher
    networks:
      - private_teacher
    ports:
      - 8000:80
  database:
    restart: unless-stopped
    image: postgres:14.1
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    networks:
      - private_teacher
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - private_teacher

networks:
  private_teacher:
    name: private_teacher
